### ISSUE TITLE
How to build winfstest.exe and fsx.exe with Nmakefile

### ISSUE THREAD

**Issue by pccq2002** [billziss-gh/secfs.test#2]
Hi,
I am grateful to you for sharing winfsp project!

I have a question:

when I use nmake.exe to build Nmake, I get some unsuccessful information.

**Comment by billziss-gh** [comment]
> I am grateful to you for sharing winfsp project!

Thank you.

> when I use nmake.exe to build Nmake, I get some unsuccessful information.

What is the exact error message you are getting?

I have a batch file in WinFsp that shows how to build the Windows components of secfs.test. I include it here for convenience:

```bat
@echo off

setlocal

set Configuration=Release
if not X%1==X set Configuration=%1

call "%VS140COMNTOOLS%\..\..\VC\vcvarsall.bat" x64

cd %~dp0..\ext\test
nmake /f Nmakefile
```

**Comment by pccq2002** [comment]
Thanks for your reply.

According to what you say, I get another output:

Microsoft (R) Program Maintenance Utility Version 14.00.24210.0
Copyright (C) Microsoft Corporation.  All rights reserved.

        cl /MT /W2 winfstest.c advapi32.lib /link /subsystem:console
Microsoft (R) C/C++ Optimizing Compiler Version 19.00.24213.1 for x64
Copyright (C) Microsoft Corporation.  All rights reserved.

winfstest.c
C:\Program Files (x86)\Windows Kits\8.1\include\\um\winnt.h(31): fatal error C10
83: Cannot open include file: 'ctype.h': No such file or directory
NMAKE : fatal error U1077: '"D:\Program Files (x86)\Microsoft Visual Studio 14.0
\VC\BIN\amd64\cl.EXE"' : return code '0x2'
Stop.

**Comment by billziss-gh** [comment]
I believe I have seen this problem before. It may be related to this:

http://stackoverflow.com/questions/31862627/vs2015-cl-cant-find-crt-libs-stido-h-ctype-h-etc-when-building-on-command-l
https://connect.microsoft.com/VisualStudio/Feedback/Details/1656623

I think this problem is fixed in latest Visual Studio 2015 update. In the past I had it fixed by marking the directory `wdf` in `C:\Program Files (x86)\Windows Kits\10\Include` as hidden.

**Comment by pccq2002** [comment]
The problem has been fixed by reinstalling win10 SDK.

Thank you very much.

**Comment by billziss-gh** [comment]
Fantastic. Let me know if you have any other problems/questions.
