### ISSUE TITLE
zzz_ResourceFork test doesn't allow xattr to truncate

### ISSUE THREAD

**Issue by jeremyspiegel** [billziss-gh/secfs.test#3]
https://github.com/billziss-gh/secfs.test/blob/e7edfb503c95998c1b0eb6b3f83ef203b1ed95dc/fstest/ntfs-3g-pjd-fstest-8af5670/tests/zzz_ResourceFork/00.t#L29

The test sets an xattr to "1234567890", then sets it to "abcd", and asserts it is equal to "abcd567890". Shouldn't it be equal to "abcd"?

My FS had behavior such that it passed this test, but exhibited a bug where removing tags via Finder behaved erratically. Fixing it to allow the value to be truncated in size fixed the Finder tag behavior.

**Comment by billziss-gh** [comment]
I seem to recall that macOS handles the resource fork specially and does not allow it to be truncated, like it would with other extended attributes.

See the last commit message here, which seems to suggest this:

https://github.com/billziss-gh/secfs.test/commits/e7edfb503c95998c1b0eb6b3f83ef203b1ed95dc/fstest/ntfs-3g-pjd-fstest-8af5670/tests/zzz_ResourceFork/00.t

**Comment by jeremyspiegel** [comment]
Yep I just verified that, thanks for pointing that out.
